{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9bd532e9-dbec-4c7c-ad8b-12e192a10d07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A:[51.135002 51.135002  0.      ]\n",
      "B:[  0.     0.   204.55]\n",
      "C:[  0.       102.270004 204.55    ]\n",
      "D:[102.270004 102.270004 204.55    ]\n",
      "E:[102.270004   0.       204.55    ]\n",
      "14754.0\n",
      "[[ 73.97      67.41     177.32    ]\n",
      " [ 13.660001  35.32     173.70001 ]\n",
      " [ 18.98      49.06     202.97    ]\n",
      " ...\n",
      " [ 34.66      14.9      184.64001 ]\n",
      " [ 12.12      70.35     185.31999 ]\n",
      " [ 12.09      83.479996 166.45001 ]]\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "import MDAnalysis as mda\n",
    "#import nglview as nv\n",
    "import numpy as np\n",
    "from IPython.core.display import Image\n",
    "import MDAnalysis.analysis.rdf\n",
    "import matplotlib.pyplot as plt\n",
    "from MDAnalysis.analysis import distances\n",
    "\n",
    "u = mda.Universe('Tip20nm_RUN.gro')\n",
    "\n",
    "SiO2 = u.select_atoms('name Si')\n",
    "minx, miny, minz = np.min(SiO2.positions,0) #find the minimum coordinates of the box\n",
    "maxx, maxy, maxz = np.max(SiO2.positions,0) #find the maximum coordinates of the box\n",
    "\n",
    "#A = np.array([(minx+maxx)/2, (miny+maxy)/2,minz])\n",
    "#B = np.array([minx, miny, maxz])\n",
    "#C = np.array([minx, maxy, maxz])\n",
    "#D = np.array([maxx, miny, maxz])\n",
    "#E = np.array([maxx, maxy, maxz])\n",
    "\n",
    "#setting the co-ordinates of all the vertices\n",
    "A = np.array([(minx+maxx)/2, (miny+maxy)/2,minz])\n",
    "B = np.array([minx, miny, maxz])\n",
    "C = np.array([minx, maxy, maxz])\n",
    "E = np.array([maxx, miny, maxz])\n",
    "D = np.array([maxx, maxy, maxz])\n",
    "\n",
    "#crossproduct to find the normal onto the plane\n",
    "nabc = -1*np.cross(C - A, B - A)\n",
    "nacd = -1*np.cross(D - A, C - A)\n",
    "nade = -1*np.cross(E - A, D - A)\n",
    "naeb = -1*np.cross(B - A, E - A)\n",
    "nbcd = -1*np.cross(C - B, D - B)\n",
    "\n",
    "inside_or_not = np.zeros([len(SiO2.positions),1]) #create a zero array to store beads that are inside the pyramid\n",
    "\n",
    "print('A:' + str(A)) #print all coordinates\n",
    "print('B:' + str(B))\n",
    "print('C:' + str(C))\n",
    "print('D:' + str(D))\n",
    "print('E:' + str(E))\n",
    "\n",
    "#dotproduct to find if the bead is inside or outside of the pyramid\n",
    "for ii in range(len(SiO2.positions)):\n",
    "    point = SiO2.positions[ii]\n",
    "    r1 = np.dot(point - A, nabc)\n",
    "    r2 = np.dot(point - A, nacd)\n",
    "    r3 = np.dot(point - A, nade)\n",
    "    r4 = np.dot(point - A, naeb)\n",
    "    r5 = np.dot(point - B, nbcd)\n",
    "    \n",
    "    all_rs = np.array([r1,r2,r3,r4,r5])\n",
    "    if np.max(all_rs)<0: #if all the dotproducts are negative then the bead is inside the pyramid or else outside the pyramid\n",
    "        inside_or_not[ii]=1\n",
    "    else:\n",
    "        inside_or_not[ii]=0\n",
    "\n",
    "print(np.sum(inside_or_not))\n",
    "\n",
    "# this is an array of zeros, that will keep track of all the positions that are inside the array\n",
    "centers_in_pyramid = np.zeros([int(np.sum(inside_or_not)),3])\n",
    "iiii=0 # a new counter\n",
    "for ii in range(len(SiO2.positions)): #go through all original SiO2 positions\n",
    "    if inside_or_not[ii]==1: #if that SiO2 position is inside the pyramid\n",
    "        centers_in_pyramid[iiii,:] = SiO2.positions[ii] #store that SiO2 position in the new rray\n",
    "        iiii +=1 #increase the counter for the new array\n",
    "\n",
    "Si_selection = u.select_atoms('name Si') #list of silicon atoms with position\n",
    "Si_selection = Si_selection[0:int(np.sum(inside_or_not))] #select only the first N SiO2 atoms, because those are the ones\n",
    "#whose positions we will replace. Here N is number of atoms inside the pyramid\n",
    "Si_selection.positions = centers_in_pyramid #replace the positions with new positions\n",
    "print(Si_selection.positions)\n",
    "\n",
    "Si_selection.write('Sqaure_pyramid_tip.gro')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2054161b-ad80-4505-8c36-0058647341c0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
